name: build

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 10 * * 1' # run "At 10:00 on Monday"

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']
        runner: ['ubuntu-latest', 'macos-latest']

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build -o /dev/null ./...

      - name: Go Test
        run: go test -v -count=1 -shuffle=on ./...

      - name: Run simplest linter
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        run: go run honnef.co/go/tools/cmd/staticcheck -checks all ./...
